### PR TITLE
Minor enhancements

### PR DESCRIPTION
**Pull request by s-sajid-ali**

### CODE REVIEW

**Review by sabasehrish — COMMENTED** [review]
@s-sajid-ali the root_mpi_wrapper doesn't seem to be much different than the mpi_wrapper. Do we really need to have two MPI applications, one for launching hepnos-based jobs and one for file-based?

**Comment by s-sajid-ali** [comment]
We could add a different flag for that and combine the two wrapper scripts into one if that's better.

**Comment by s-sajid-ali** [comment]
This is now ready for review @sabasehrish. Let me know if you have any other suggestions.

**Comment by s-sajid-ali** [comment]
Ping @sabasehrish : Can this be merged now? I'll rebase the other PR against the primary branch once this is merged.

**Pull request merged**
